### ISSUE TITLE
not installing on docker or though pip. t

### ISSUE THREAD

**Issue by kadolis** [DarrenWestwood/greed#48] opened 2022-11-30 05:01 UTC
I am aware that installation instrutctions we were redirected to the original repo, but i think this error has something to do with the BTC system... although i really have no idea what. the toml module is bugging out with the config. if someone could help me out with this i would appreciate it. 

thon3 (3.8.2-4) ...
killua@machine:~/greed$ python -OO core.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/usr/local/lib/python3.8/dist-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/usr/local/lib/python3.8/dist-packages/toml/decoder.py", line 812, in load_value
    raise ValueError("Empty value is invalid")
ValueError: Empty value is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.py", line 13, in <module>
    import worker
  File "/home/killua/greed/worker.py", line 14, in <module>
    from blockonomics import Blockonomics
  File "/home/killua/greed/blockonomics.py", line 2, in <module>
    import configloader
  File "/home/killua/greed/configloader.py", line 31, in <module>
    user_cfg = nuconfig.NuConfig(user_cfg_file)
  File "/home/killua/greed/nuconfig.py", line 12, in __init__
    self.data = toml.load(file)
  File "/usr/local/lib/python3.8/dist-packages/toml/decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "/usr/local/lib/python3.8/dist-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Empty value is invalid (line 63 column 1 char 2538)

**Comment by DarrenWestwood** [comment] 2022-11-30 10:35
Hi @kadolis,

Installation using docker is currently not supported, however, this will be included in the future. Until then, please use `pip` for installation.

There appears to be an issue with your `config/config.toml` file. The error indicates you may have an empty value in your config on [line 63](https://github.com/DarrenWestwood/greed/blob/master/config/template_config.toml#L63). Please either comment out this line again or fill in a value.

Please let me know if this solves your issue.

Kind regards

**Comment by kadolis** [comment] 2022-11-30 15:19
Thanks @DarrenWestwood , It was the credit card API key when you want credit cards disabled you need to include the " " or else the program wont start.

**Comment by DarrenWestwood** [comment] 2023-05-09 14:30
Thanks @kadolis for letting me know the cause of the issue. The default value is now shown to be an empty string in the latest greed updates: https://github.com/DarrenWestwood/greed/blob/master/config/template_config.toml#L73-L74
Closing this issue now.

**Closed by DarrenWestwood** 2023-05-09 14:30 UTC
