### ISSUE TITLE
Error when accesing product as a customer

### ISSUE THREAD

**Issue by Nisaba** [DarrenWestwood/greed#53] opened 2023-01-18 14:06 UTC
Hello,

I've an error when, as a customer, I select the "Order products" item : 

self.__user_menu()
File "/opt/greed/worker.py", line 480, in __user_menu
self.__order_menu()
File "/opt/greed/worker.py", line 518, in __order_menu
cart[message['result']['message_id']] = [product, 0]
KeyError: 'result'

Note : I have only one product on my catalog

Thank you for your help

**Comment by DarrenWestwood** [comment] 2023-01-20 13:56
Hi @Nisaba ,

This error does not appear related to bitcoin payments and may be part of the [main repo](https://github.com/Steffo99/greed). This appears to be an issue with displaying the product as a telegram message: https://github.com/DarrenWestwood/greed/blob/master/database.py#L136-L140

Please try edit the product and remove the image before testing again. Let me know if removing the product image solves the error.

**Comment by Nisaba** [comment] 2023-01-28 17:07
Hello,
Thank you for your feedback.
The issue was about the product description that was too long.
The description is now shorter and it works at this point.

But now it crashes when I add the product to the cart, with this error :
Full error: Media_caption_too_long

So do you know what is the max length of the description of a product ?
Thanks

**Comment by DarrenWestwood** [comment] 2023-05-09 14:26
Thanks @Nisaba  for letting me know the product description was the cause. Closing this issue.

**Closed by DarrenWestwood** 2023-05-09 14:26 UTC
